toggleEffectsStatus = true
colorMode = "Effect"
toggleMovementStatus = false
toggleEquipmentStatus = false

[uiConfig]
toggleSimpleHUDEnhanced = true
textColor = 16777215
textBackground = false
textScale = 90
textAlignment = "Right"

[statusElements]
Xcords = 100
Ycords = 98
toggleLightLevel = false
togglePlayerName = false
togglePing = false
toggleTPS = false
toggleServerName = false
toggleServerAddress = false

[statusElements.coordinates]
toggleCoordinates = false
toggleDirection = false
toggleOffset = false
toggleNetherCoordinateConversion = false
toggleChunkCoordinates = false
toggleSubChunkCoordinates = false

[statusElements.fps]
toggleFPS = true
toggleColourFPS = false

[statusElements.playerSpeed]
togglePlayerSpeed = false
togglePlayerVerticalSpeed = false

[statusElements.Biome]
toggleBiome = false
toggleBiomeLabel = false

[statusElements.gameTime]
toggleGameTime = false
toggleGameTime24Hour = false
toggleGameDayCounter = false

[statusElements.systemTime]
toggleSystemTime = true
textScale = 100
textBackground = false
toggleSystemTime24Hour = true

[statusElements.counters]
toggleEntityCount = false
toggleParticleCount = false

[statusElements.counters.chunkCount]
toggleChunkCount = false
toggleTotal = true
toggleLoaded = true

[effectsStatus]
backgroundColor = -2147483648
beneficialForegroundColor = -2130706433
harmfulForegroundColor = -2130706433
neutralForegroundColor = -2130706433

[movementStatus]
toggleMovementStatus = false
textScale = 100
movementStatusLocationX = 0
movementStatusLocationY = 90

[movementStatus.movementTypes]
toggleSprintStatus = true
toggleSneakStatus = true
toggleFlyingStatus = true
toggleSwimmingStatus = true

[paperDoll]
togglePaperDoll = true
textScale = 100
paperDollLocationX = 100
paperDollLocationY = 0

[equipmentStatus]
showCount = true
showNonTools = true
textScale = 100
equipmentOrientation = "Vertical"
equipmentAlignment = "Auto"
equipmentStatusLocationX = 0
equipmentStatusLocationY = 60

[equipmentStatus.Durability]
showDurability = true
showTotalCount = false
showDurabilityAsPercentage = false
showColour = true
showDurabilityAsBar = true

[equipmentStatus.Durability.slots]
Head = true
Body = true
Legs = true
Boots = true
OffHand = true
MainHand = true

[equipmentStatus.slots]
Head = true
Body = true
Legs = true
Boots = true
OffHand = true
MainHand = true
