[light_sources]
	water_sensitive_check = true
	self = true
	block_entities = true
	entities = true

			[light_sources.settings.entities.minecraft]
				panda = true
				axolotl = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				llama = true
				bat = true
				husk = true
				frog = true
				hoglin = true
				armadillo = true
				rabbit = true
				firework_rocket = true
				armor_stand = true
				drowned = true
				experience_orb = true
				item = true
				turtle = true
				salmon = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				item_frame = true
				horse = true
				phantom = true
				minecart = true
				glow_squid = true
				glow_item_frame = true
				squid = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				bogged = true
				tropical_fish = true
				chest_minecart = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				piglin = true
				blaze = true
				cat = true
				zombie = true
				ender_pearl = true
				ghast = true
				sheep = true
				fireball = true
				player = true
				trident = true
				wither_skull = true
				wolf = true
				villager = true
				skeleton_horse = true
				zombie_villager = true
				boat = true
				small_fireball = true
				strider = true
				polar_bear = true
				hopper_minecart = true
				painting = true
				witch = true
				spider = true
				wither = true
